// <auto-generated />
namespace GuaritaVisitantes.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Visitante05 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Visitante05));
        
        string IMigrationMetadata.Id
        {
            get { return "202107211732445_Visitante05"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
