// <auto-generated />
namespace GuaritaVisitantes.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Visitante02 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Visitante02));
        
        string IMigrationMetadata.Id
        {
            get { return "202107131933035_Visitante02"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
